### ISSUE TITLE
Loop example output is inaccurate

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/nested-arrays-ruby#18]
The example states:

> In order to manipulate or operate on each element of a nested array, we must iterate down into that level of the array. For example, if you run the following code in IRB:
> 
> ```
> nested_students.each do |student_array|
>   puts student_array
> end
> ```
> 
> You will have outputted:
> 
> ```
> ["Mike", "Grade 10", "A average"]
> ["Tim", "Grade 10", "C average"]
> ["Monique", "Grade 11", "B average", "Class President"]
> ```

However, IRB gives a different result:

```
2.2.4 :001 > nested_students = [
2.2.4 :002 >       ["Mike", "Grade 10", "A average"],
2.2.4 :003 >       ["Tim", "Grade 10", "C average"],
2.2.4 :004 >       ["Monique", "Grade 11", "B average", "Class President"]
2.2.4 :005?>   ]
 => [["Mike", "Grade 10", "A average"], ["Tim", "Grade 10", "C average"], ["Monique", "Grade 11", "B average", "Class President"]]
2.2.4 :006 > nested_students.each do |student_array|
2.2.4 :007 >       puts student_array
2.2.4 :008?>   end
Mike
Grade 10
A average
Tim
Grade 10
C average
Monique
Grade 11
B average
Class President
 => [["Mike", "Grade 10", "A average"], ["Tim", "Grade 10", "C average"], ["Monique", "Grade 11", "B average", "Class President"]]
```

In order to achieve the output given in the example, one must use `#inspect`:

```
2.2.4 :009 > nested_students.each do |student_array|
2.2.4 :010 >     puts student_array.inspect
2.2.4 :011?>   end
["Mike", "Grade 10", "A average"]
["Tim", "Grade 10", "C average"]
["Monique", "Grade 11", "B average", "Class President"]
 => [["Mike", "Grade 10", "A average"], ["Tim", "Grade 10", "C average"], ["Monique", "Grade 11", "B average", "Class President"]]
```

Therefore, this section should be revised.

**Comment by jnoconor** [comment]
Seconding this issue. `student_array.to_s` also works, of course.

**Comment by AnnJohn** [comment]
@ivalentine can you make a PR for this if possible? Thanks
