### ISSUE TITLE
"More Nested Arrays"

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/nested-arrays-ruby#19]
the sentence:
Let's take a look at some multidimensional arrays that have an even deeper
nested than the 2D arrays we've just practiced with.

seems more grammatically correct to say:
Let's take a look at some multidimensional arrays that "are" even deeper
nested than the 2D arrays we've just practiced with.

**Comment by AnnJohn** [comment]
thanks! we updated it.
