### ISSUE TITLE
Missing Paragraph

### ISSUE THREAD

**Issue by aybakes** [learn-co-curriculum/nested-arrays-ruby#22]
It seems that there should be some information written under this paragraph heading: READING AND WRITING WITH NESTED ARRAYS
Nothing is showing up for me.

**Comment by AnnJohn** [comment]
hi @MichelleBakels that's a formatting issue with Learn and there is no content missing. The larger issue is that the heading below it should be smaller but right now, the two headings render as the same size. We're aware of it and will fix soon. Thanks!
