### ISSUE TITLE
Binding.pry not covered in any of the lessons before in this track

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/nested-arrays-ruby#3]
At the end of the lesson, it's mentioned and should be removed. Don't think it's worth introducing now for this track. 

![screen shot 2015-09-29 at 9 59 39 am](https://cloud.githubusercontent.com/assets/1892150/10166185/e2f67fe6-6690-11e5-9075-1726ea996d95.png)

**Comment by aviflombaum** [comment]
fixed 73b732b
